[env]
TERM = "xterm-256color"

[window]
opacity = 1.0 

[font]
normal = {family = "Commit Mono Nerd Font Propo"}

# midnight-haze

# Default colors
[colors.primary]
background = '#0c0c16'
foreground = '#d8dee9'

# Normal colors
[colors.normal]
black   = '#2c2c3d'
red     = '#ff6e6e'
green   = '#9ec875'
yellow  = '#ffa759'
blue    = '#70a7d4'
magenta = '#d291e0'
cyan    = '#96e0e0'
white   = '#d8dee9'

# Bright colors
[colors.bright]
black   = '#414166'
red     = '#ff8d8d'
green   = '#b3d987'
yellow  = '#ffc57f'
blue    = '#9bb3d3'
magenta = '#ffa1ff'
cyan    = '#9cd8d8'
white   = '#ffffff'

# Colours (Monokai Charcoal)

# Default Colours
#[colors.primary]
#background = '#000000'
#foreground = '#FFFFFF'

# Normal Colours
#[colors.normal]
#black   = '#1a1a1a'
#red     = '#f4005f'
#green   = '#98e024'
#yellow  = '#fa8419'
#blue    = '#9d65ff'
#magenta = '#f4005f'
#cyan    = '#58d1eb'
#white   = '#c4c5b5'

# Bright Colours
#[colors.bright]
#black   = '#625e4c'
#red     = '#f4005f'
#green   = '#98e024'
#yellow  = '#e0d561'
#blue    = '#9d65ff'
#magenta = '#f4005f'
#cyan    = '#58d1eb'
#white   = '#f6f6ef'
